# -*- coding: utf-8 -*-
"""Stock_Time_Series_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBxiTebZtorNDYDXM-ID-t6SVlVBU9KP
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load dataset (update path if needed)
file_path = "/content/ML471_S1_Datafile_Practice.csv"
df = pd.read_csv(file_path)

# Parse Date column and set as index
df['Date'] = pd.to_datetime(df['Date'])
df.set_index('Date', inplace=True)

df.head()

# Plot Closing Price Over Time
plt.figure(figsize=(10, 5))
plt.plot(df.index, df['Close'])
plt.title("Stock Price Over Time")
plt.xlabel("Date")
plt.ylabel("Close Price")
plt.show()

